### ISSUE TITLE
yellowstone-grpc-proto 2.0.0 dependency resolution fails

### ISSUE THREAD

**Issue by thiras** [rpcpool/yellowstone-grpc#451]
```toml
[package]
name = "test-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
yellowstone-grpc-proto = "2.0.0"
```

`cargo build` throw this error;

```
Updating crates.io index
error: failed to select a version for `zeroize`.
    ... required by package `ed25519-dalek v1.0.1`
    ... which satisfies dependency `ed25519-dalek = "=1.0.1"` of package `solana-sdk v2.0.10`
    ... which satisfies dependency `solana-sdk = "=2.0.10"` of package `solana-account-decoder v2.0.10`
    ... which satisfies dependency `solana-account-decoder = "~2.0.10"` of package `yellowstone-grpc-proto v2.0.0`
    ... which satisfies dependency `yellowstone-grpc-proto = "^2.0.0"` of package `fortunate-rs v0.1.0 (/home/thiras/dev/test/test-rs)`
versions that meet the requirements `^1` (locked to 1.8.1) are: 1.8.1

all possible versions conflict with previously selected packages.

  previously selected package `zeroize v1.0.0`
    ... which satisfies dependency `zeroize = ">=1, <1.4"` of package `curve25519-dalek v3.2.1`
    ... which satisfies dependency `curve25519-dalek = "^3.2.1"` of package `solana-program v2.0.10`
    ... which satisfies dependency `solana-program = "=2.0.10"` of package `solana-sdk v2.0.10`
    ... which satisfies dependency `solana-sdk = "=2.0.10"` of package `solana-account-decoder v2.0.10`
    ... which satisfies dependency `solana-account-decoder = "~2.0.10"` of package `yellowstone-grpc-proto v2.0.0`
    ... which satisfies dependency `yellowstone-grpc-proto = "^2.0.0"` of package `fortunate-rs v0.1.0 (/home/thiras/dev/test/test-rs)`

failed to select a version for `zeroize` which could resolve this conflict
```

**Comment by thiras** [comment]
It worked with `default-features = false`

```toml
[dependencies]
yellowstone-grpc-proto = { version = "2.0.0", default-features = false }
```
